In [4]:
import sqlite3



# Create a SQL connection to our SQLite database

con = sqlite3.connect(r"C:\Users\Administrator\Downloads\chinook.db")



cur = con.cursor()



# The result of a "cursor.execute" can be iterated over by row

for row in cur.execute('SELECT * FROM Movies;'):

  print(row)



   



# Be sure to close the connection

con.close()

(901, 'Vertigo', 1958, 128, 'English', '1958-08-24', 'UK', 'Righty Sock', 9001, '8.4', '263575')
(902, 'The Innocents', 1961, 100, 'English', '1962-02-19', 'SW', 'Jack Malvern', 9002, '7.9', '20207')
(903, 'Lawrence of Arabia', 1962, 216, 'English', '1962-12-11', 'UK', 'Flagrant Baronessa', 9003, '8.3', '202778')
(904, 'The Deer Hunter', 1978, 183, 'English', '1979-03-08', 'UK', 'Alec Shaw', 9005, '8.2', '484746')
(905, 'Amadeus', 1984, 160, 'English', '1985-01-07', 'UK', 'Francois Truffaut', 9006, '7.3', None)
(906, 'Blade Runner', 1982, 117, 'English', '1982-09-09', 'UK', 'Victor Woeltjen', 9007, '8.6', '779489')
(907, 'Eyes Wide Shut', 1999, 159, 'English', None, 'UK', 'Simon Wright', 9008, None, '227235')
(908, 'The Usual Suspects', 1995, 106, 'English', '1995-08-25', 'UK', 'Neal Wruck', 9009, '3', '195961')
(909, 'Chinatown', 1974, 130, 'English', '1974-08-09', 'UK', 'Paul Monks', 9010, '8.1', '203875')
(910, 'Boogie Nights', 1997, 155, 'English', '1998-02-16', 'UK', 'Mike Salvati', 9011, '8.4', None)
(911, 'Annie Hall', 1977, 93, 'English', '1977-04-20', 'USA', 'Armond White', 9013, '7', '862618')
(912, 'Princess Mononoke', 1997, 134, 'Japanese', '2001-10-19', 'UK', 'Wesley S. Walker', 9001, '7.7', '830095')
(913, 'The Shawshank Redemption', 1994, 142, 'English', '1995-02-17', 'UK', 'Sasha Goldshtein', 9014, '4', '642132')
(914, 'American Beauty', 1999, 122, 'English', None, 'UK', 'Josh Cates', 9015, '7.7', '81328')
(915, 'Titanic', 1997, 194, 'English', '1998-01-23', 'UK', 'Krug Stillo', 9016, None, '580301')
(916, 'Good Will Hunting', 1997, 126, 'English', '1998-06-03', 'UK', 'Scott LeBrun', 9017, '8.1', '609451')
(917, 'Deliverance', 1972, 109, 'English', '1982-10-05', 'UK', 'Hannah Steele', 9018, '8', '667758')
(918, 'Trainspotting', 1996, 94, 'English', '1996-02-23', 'UK', 'Vincent Cadena', 9019, '8.4', '511613')
(919, 'The Prestige', 2006, 130, 'English', '2006-11-10', 'UK', 'Brandt Sponseller', 9020, '6.7', '13091')
(920, 'Donnie Darko', 2001, 113, 'English', None, 'UK', 'Richard Adams', 9021, '7', '544452')
(921, 'Slumdog Millionaire', 2008, 120, 'English', '2009-01-09', 'UK', 'Andre Bazin', 9022, '7', '557054')
(922, 'Aliens', 1986, 137, 'English', '1986-08-29', 'UK', 'Judith Christ', 9023, '7', '569657')
(923, 'Beyond the Sea', 2004, 118, 'English', '2004-11-26', 'UK', 'Peter Travers', 9024, '6.9', '582260')
(924, 'Avatar', 2009, 162, 'English', '2009-12-17', 'UK', 'Roger Ebert', 9025, '6.9', '594862')
(926, 'Seven Samurai', 1954, 207, 'Japanese', '1954-04-26', 'JP', 'Pauline Kael', 9026, '6.9', '607465')
(927, 'Spirited Away', 2001, 125, 'Japanese', '2003-09-12', 'UK', 'Leonard Martin', 9027, '6.8', '620067')
(928, 'Back to the Future', 1985, 116, 'English', '1985-12-04', 'UK', 'Andrew Sarris', 9028, '6.8', '632670')
(925, 'Braveheart', 1995, 178, 'English', '1995-09-08', 'UK', 'Gene Shalit', 9029, '6.8', '645273')

In [5]:
import pandas as pd
con = sqlite3.connect (r"C:\Users\Administrator\Downloads\chinook.db")
cur = con.cursor()
for row in cur.execute('SELECT * FROM Movies;'):
    print(row)

(901, 'Vertigo', 1958, 128, 'English', '1958-08-24', 'UK', 'Righty Sock', 9001, '8.4', '263575')
(902, 'The Innocents', 1961, 100, 'English', '1962-02-19', 'SW', 'Jack Malvern', 9002, '7.9', '20207')
(903, 'Lawrence of Arabia', 1962, 216, 'English', '1962-12-11', 'UK', 'Flagrant Baronessa', 9003, '8.3', '202778')
(904, 'The Deer Hunter', 1978, 183, 'English', '1979-03-08', 'UK', 'Alec Shaw', 9005, '8.2', '484746')
(905, 'Amadeus', 1984, 160, 'English', '1985-01-07', 'UK', 'Francois Truffaut', 9006, '7.3', None)
(906, 'Blade Runner', 1982, 117, 'English', '1982-09-09', 'UK', 'Victor Woeltjen', 9007, '8.6', '779489')
(907, 'Eyes Wide Shut', 1999, 159, 'English', None, 'UK', 'Simon Wright', 9008, None, '227235')
(908, 'The Usual Suspects', 1995, 106, 'English', '1995-08-25', 'UK', 'Neal Wruck', 9009, '3', '195961')
(909, 'Chinatown', 1974, 130, 'English', '1974-08-09', 'UK', 'Paul Monks', 9010, '8.1', '203875')
(910, 'Boogie Nights', 1997, 155, 'English', '1998-02-16', 'UK', 'Mike Salvati', 9011, '8.4', None)
(911, 'Annie Hall', 1977, 93, 'English', '1977-04-20', 'USA', 'Armond White', 9013, '7', '862618')
(912, 'Princess Mononoke', 1997, 134, 'Japanese', '2001-10-19', 'UK', 'Wesley S. Walker', 9001, '7.7', '830095')
(913, 'The Shawshank Redemption', 1994, 142, 'English', '1995-02-17', 'UK', 'Sasha Goldshtein', 9014, '4', '642132')
(914, 'American Beauty', 1999, 122, 'English', None, 'UK', 'Josh Cates', 9015, '7.7', '81328')
(915, 'Titanic', 1997, 194, 'English', '1998-01-23', 'UK', 'Krug Stillo', 9016, None, '580301')
(916, 'Good Will Hunting', 1997, 126, 'English', '1998-06-03', 'UK', 'Scott LeBrun', 9017, '8.1', '609451')
(917, 'Deliverance', 1972, 109, 'English', '1982-10-05', 'UK', 'Hannah Steele', 9018, '8', '667758')
(918, 'Trainspotting', 1996, 94, 'English', '1996-02-23', 'UK', 'Vincent Cadena', 9019, '8.4', '511613')
(919, 'The Prestige', 2006, 130, 'English', '2006-11-10', 'UK', 'Brandt Sponseller', 9020, '6.7', '13091')
(920, 'Donnie Darko', 2001, 113, 'English', None, 'UK', 'Richard Adams', 9021, '7', '544452')
(921, 'Slumdog Millionaire', 2008, 120, 'English', '2009-01-09', 'UK', 'Andre Bazin', 9022, '7', '557054')
(922, 'Aliens', 1986, 137, 'English', '1986-08-29', 'UK', 'Judith Christ', 9023, '7', '569657')
(923, 'Beyond the Sea', 2004, 118, 'English', '2004-11-26', 'UK', 'Peter Travers', 9024, '6.9', '582260')
(924, 'Avatar', 2009, 162, 'English', '2009-12-17', 'UK', 'Roger Ebert', 9025, '6.9', '594862')
(926, 'Seven Samurai', 1954, 207, 'Japanese', '1954-04-26', 'JP', 'Pauline Kael', 9026, '6.9', '607465')
(927, 'Spirited Away', 2001, 125, 'Japanese', '2003-09-12', 'UK', 'Leonard Martin', 9027, '6.8', '620067')
(928, 'Back to the Future', 1985, 116, 'English', '1985-12-04', 'UK', 'Andrew Sarris', 9028, '6.8', '632670')
(925, 'Braveheart', 1995, 178, 'English', '1995-09-08', 'UK', 'Gene Shalit', 9029, '6.8', '645273')

In [6]:
cur.execute('SELECT * FROM Movies;')


df = pd.DataFrame(cur.fetchall())


df

,0,1,2,3,4,5,6,7,8,9,10
0,901,Vertigo,1958,128,English,1958-08-24,UK,Righty Sock,9001,8.4,263575
1,902,The Innocents,1961,100,English,1962-02-19,SW,Jack Malvern,9002,7.9,20207
2,903,Lawrence of Arabia,1962,216,English,1962-12-11,UK,Flagrant Baronessa,9003,8.3,202778
3,904,The Deer Hunter,1978,183,English,1979-03-08,UK,Alec Shaw,9005,8.2,484746
4,905,Amadeus,1984,160,English,1985-01-07,UK,Francois Truffaut,9006,7.3,None
5,906,Blade Runner,1982,117,English,1982-09-09,UK,Victor Woeltjen,9007,8.6,779489
6,907,Eyes Wide Shut,1999,159,English,None,UK,Simon Wright,9008,None,227235
7,908,The Usual Suspects,1995,106,English,1995-08-25,UK,Neal Wruck,9009,3,195961
8,909,Chinatown,1974,130,English,1974-08-09,UK,Paul Monks,9010,8.1,203875
9,910,Boogie Nights,1997,155,English,1998-02-16,UK,Mike Salvati,9011,8.4,None
10,911,Annie Hall,1977,93,English,1977-04-20,USA,Armond White,9013,7,862618
11,912,Princess Mononoke,1997,134,Japanese,2001-10-19,UK,Wesley S. Walker,9001,7.7,830095
12,913,The Shawshank Redemption,1994,142,English,1995-02-17,UK,Sasha Goldshtein,9014,4,642132
13,914,American Beauty,1999,122,English,None,UK,Josh Cates,9015,7.7,81328
14,915,Titanic,1997,194,English,1998-01-23,UK,Krug Stillo,9016,None,580301
15,916,Good Will Hunting,1997,126,English,1998-06-03,UK,Scott LeBrun,9017,8.1,609451
16,917,Deliverance,1972,109,English,1982-10-05,UK,Hannah Steele,9018,8,667758
17,918,Trainspotting,1996,94,English,1996-02-23,UK,Vincent Cadena,9019,8.4,511613
18,919,The Prestige,2006,130,English,2006-11-10,UK,Brandt Sponseller,9020,6.7,13091
19,920,Donnie Darko,2001,113,English,None,UK,Richard Adams,9021,7,544452
20,921,Slumdog Millionaire,2008,120,English,2009-01-09,UK,Andre Bazin,9022,7,557054
21,922,Aliens,1986,137,English,1986-08-29,UK,Judith Christ,9023,7,569657
22,923,Beyond the Sea,2004,118,English,2004-11-26,UK,Peter Travers,9024,6.9,582260
23,924,Avatar,2009,162,English,2009-12-17,UK,Roger Ebert,9025,6.9,594862
24,926,Seven Samurai,1954,207,Japanese,1954-04-26,JP,Pauline Kael,9026,6.9,607465
25,927,Spirited Away,2001,125,Japanese,2003-09-12,UK,Leonard Martin,9027,6.8,620067
26,928,Back to the Future,1985,116,English,1985-12-04,UK,Andrew Sarris,9028,6.8,632670
27,925,Braveheart,1995,178,English,1995-09-08,UK,Gene Shalit,9029,6.8,645273